CREATE TABLE ACCOUNT (ID  SERIAL NOT NULL, PRINCIPAL VARCHAR(32) NOT NULL UNIQUE, NAME VARCHAR(16) NOT NULL, DESCRIPTION TEXT NOT NULL, STATUS VARCHAR(16) NOT NULL, MODIFIED TIMESTAMP NOT NULL, CREATED TIMESTAMP NOT NULL, PRIMARY KEY (ID));
CREATE INDEX INDEX_ACCOUNT_STATUS ON ACCOUNT (STATUS);
CREATE INDEX INDEX_ACCOUNT_CREATED ON ACCOUNT (CREATED);
